sudo: true
language: python
python:
  - "3.5"
  - "3.6"
install: pip install tox-travis
script:
  - tox
  # This is not in included in the tox envlist, in order to don't need Internet
  # when running tox
  - tox -e doclinks
  - tox -e clean

before_install:
    - gpg --version
    - gpg --keyserver hkp://ha.pool.sks-keyservers.net --recv A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    - gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add
    - echo "deb https://deb.torproject.org/torproject.org trusty main" | sudo tee -a /etc/apt/sources.list
    - echo "deb-src https://deb.torproject.org/torproject.org trusty main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install tor -y

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-ci"
    template:
      - "%{repository_slug} %{branch} %{commit} - %{author}: %{commit_subject}"
      - "Build #%{build_number} %{result}. Details: %{build_url}"

# To build the docs
addons:
  apt:
    packages:
    - texlive-latex-extra
    - dvipng
